sudo: require # yêu cầu quyền cao nhất trong quá trình thực hiện
services:  #nói với travis cần 1 bản copy của docker để chạy quá trình này
  - docker

before_install: #xây dựng 1 image thông qua file Dockerfile.dev
  - docker build -t tuanminh/docker-react -f Dockerfile.dev .
script: #nói với travis cách chạy các bài test
  - docker run -e CI=true tuanminh/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk #tên nền tảng
  region: 'us-east-1' #tên vùng kho khởi tạo ứng dụng
  app: 'Docker-react' #tên app
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-225317789430', #S3 -> app
  bucket_path: 'Docker-react'
  on: #chỉ redeploy ở nhánh được chỉ định
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY